
import { GoogleGenAI, Type, Modality } from "@google/genai";

export class GeminiService {
  constructor() {}

  // Fast AI Response using Gemini 2.5 Flash Lite
  async askFastAi(prompt: string) {
    // Create a new instance right before the call to ensure the latest API key is used
    const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-lite-latest',
      contents: prompt,
    });
    return response.text;
  }

  // Generate an image using nano banana series models
  async generateImage(prompt: string, config: { aspectRatio?: string; imageSize?: string }) {
    // Select model based on quality requirements
    const model = config.imageSize === '2K' || config.imageSize === '4K' 
      ? 'gemini-3-pro-image-preview' 
      : 'gemini-2.5-flash-image';
    
    const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
    const response = await ai.models.generateContent({
      model,
      contents: { parts: [{ text: prompt }] },
      config: {
        imageConfig: {
          aspectRatio: (config.aspectRatio as any) || "1:1",
          imageSize: (config.imageSize as any) || "1K"
        }
      }
    });

    // Iterate through response parts to find the generated image
    const candidate = response.candidates?.[0];
    if (candidate?.content?.parts) {
      for (const part of candidate.content.parts) {
        if (part.inlineData) {
          return `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`;
        }
      }
    }
    throw new Error("No image was generated by the model.");
  }

  // Edit an image using text prompt and source image
  async editImage(prompt: string, base64Data: string, mimeType: string) {
    const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          {
            inlineData: {
              data: base64Data,
              mimeType: mimeType,
            },
          },
          {
            text: prompt,
          },
        ],
      },
    });

    const candidate = response.candidates?.[0];
    if (candidate?.content?.parts) {
      for (const part of candidate.content.parts) {
        if (part.inlineData) {
          return `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`;
        }
      }
    }
    throw new Error("Failed to edit the image.");
  }

  // Generate a video using the Veo model
  async generateVideo(prompt: string, options: { aspectRatio?: '16:9' | '9:16'; image?: { data: string; mimeType: string } }) {
    const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
    
    // Initiate video generation operation
    let operation = await ai.models.generateVideos({
      model: 'veo-3.1-fast-generate-preview',
      prompt: prompt || undefined,
      image: options.image ? {
        imageBytes: options.image.data,
        mimeType: options.image.mimeType,
      } : undefined,
      config: {
        numberOfVideos: 1,
        resolution: '720p',
        aspectRatio: options.aspectRatio || '16:9'
      }
    });

    // Polling for the operation to complete (standard 10s intervals)
    while (!operation.done) {
      await new Promise(resolve => setTimeout(resolve, 10000));
      operation = await ai.operations.getVideosOperation({ operation: operation });
    }

    const downloadLink = operation.response?.generatedVideos?.[0]?.video?.uri;
    if (!downloadLink) throw new Error("Video generation failed or returned no URI.");

    // Fetch the video file using the API key
    const response = await fetch(`${downloadLink}&key=${process.env.API_KEY}`);
    if (!response.ok) throw new Error(`Failed to download video: ${response.statusText}`);
    
    const blob = await response.blob();
    return URL.createObjectURL(blob);
  }
}

export const gemini = new GeminiService();
